using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace BackendServices.Models;

public class Category
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }  // Auto-generated by MongoDB
        
    public string Name { get; set; }  // Name of the category
}